### ISSUE TITLE
When I use plugin tab this plugin is not working

### ISSUE THREAD

**Issue by sdawd2q3e** [DavideBlade/HealthBar-Reloaded#5] opened 2023-07-02 14:24 UTC
When I use plugin tab this plugin is not working

**Comment by sdawd2q3e** [comment] 2023-07-02 14:24
https://modrinth.com/plugin/tab-was-taken

**Comment by sdawd2q3e** [comment] 2023-07-02 14:28
Placeholders do not work

**Comment by DavideBlade** [comment] 2023-07-04 21:09
It is likely that the reason is because this plugin also uses Scoreboards and so they conflict. I will try to contact the developer to see what can be done but there may be no workable solution.

**Comment by DavideBlade** [comment] 2023-07-04 21:12
Can you send me screenshots of what the tab looks like when you are not using HealthBar and when it is present?

**Comment by sdawd2q3e** [comment] 2023-07-04 21:14
It shows only the things that you put in the tab only, but heal does not work. Try that and you will see what happens

**Comment by sdawd2q3e** [comment] 2023-07-11 16:32
Did you find a solution to the problem?

**Comment by DavideBlade** [comment] 2023-07-12 09:26
I could not find the developer's contact through any channel, so the problem is currently stalled. I will have to study the plugin and that will take quite some time.

**Comment by DavideBlade** [comment] 2024-06-22 17:06
If support is still needed, please provide me with a screenshot explaining where the problem is. I am not familiar with the plugin and have never used it, so I don't know what works or what doesn't.
Also, what version of the plugins and Spigot are you using? What is your configuration?

**Comment by DavideBlade** [comment] 2024-07-05 06:38
No answer. Closing.

**Closed as not planned by DavideBlade** 2024-07-05 06:38 UTC
Labels: invalid
